STG_AUDIT = """
        AUDIT_CREATED_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
        AUDIT_CREATED_BY VARCHAR(50) NOT NULL,
        ETL_BATCH_ID NUMBER(38,0) NOT NULL);
            """

TYPE_2 = """
    ACTIVE_FLAG VARCHAR(1) NOT NULL,
    EFFECTIVE_START_DATE TIMESTAMP_NTZ(9) NOT NULL,
    EFFECTIVE_END_DATE TIMESTAMP_NTZ(9),
        """

AUDIT_CONSTRAINT1 = """
    AUDIT_CREATED_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
    AUDIT_UPDATED_DATETIME TIMESTAMP_NTZ(9),
    AUDIT_CREATED_BY VARCHAR(50) NOT NULL,
    AUDIT_UPDATED_BY VARCHAR(50),
    ETL_BATCH_ID NUMBER(38,0) NOT NULL,
    HASH_KEY NUMBER(38,0),
    """
    
AUDIT_CONSTRAINT2 = """
    AUDIT_CREATED_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
    AUDIT_CREATED_BY VARCHAR(50) NOT NULL,
    ETL_BATCH_ID NUMBER(38,0) NOT NULL,
            """

AUDIT1 = """
    AUDIT_CREATED_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
    AUDIT_UPDATED_DATETIME TIMESTAMP_NTZ(9),
    AUDIT_CREATED_BY VARCHAR(50) NOT NULL,
    AUDIT_UPDATED_BY VARCHAR(50),
    ETL_BATCH_ID NUMBER(38,0) NOT NULL,
    HASH_KEY NUMBER(38,0));
            """

AUDIT2 = """
    AUDIT_CREATED_DATETIME TIMESTAMP_NTZ(9) NOT NULL,
    AUDIT_CREATED_BY VARCHAR(50) NOT NULL,
    ETL_BATCH_ID NUMBER(38,0) NOT NULL);
            """

